name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd pres && make

    - uses: actions/upload-artifact@v2
      with:
        name: presentation.pdf
        path: pres/pres.pdf
